name: subworkflow-name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: install go modules
        run: go mod download
        
      - name: Clear Go mod cache
        run: go clean -modcache

      - name: Install Swag
        run: go get -u github.com/swaggo/swag/cmd/swag && go install github.com/swaggo/swag/cmd/swag

      - name: Swag init
        run: swag init

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Build PostgreSQL container
        run: docker-compose up -d

      - name: Build and test
        run: go build ./... && go test ./...
